# docker-compose.yml

version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
    expose:
      - 8000

  ui:
    stdin_open: true
    build: ./ui
    volumes:
      - ./ui:/usr/src/app
      - /usr/src/app/node_modules
    expose:
      - 3000
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  reverse_proxy:
    build: ./server
    ports:
      - 81:80
    depends_on:
      - backend
      - ui