FROM node:10-alpine
MAINTAINER Robert Wells <rwells@dvele.com>

WORKDIR /tmp
COPY front/package.json /tmp/

ENV NODE_ENV=production

RUN npm install

WORKDIR /app
COPY ./front /app/

COPY /conf/react/nginx.conf /app/

RUN yarn run build:prod

FROM nginx:1.17.5-alpine
COPY --from=build /app/build /app/
COPY --from=build /app/nginx.conf /etc/nginx/nginx.conf
EXPOSE 80
EXPOSE 443

CMD ["nginx", "-g", "daemon off;"]
